### ISSUE TITLE
XGrabKeyboard support

### ISSUE THREAD

**Issue by blak3mill3r** [moaxcp/x11#25]
At a glance I couldn't find any evidence that `XGrabKeyboard` is supported. Did I miss something? What would it take to add it?

**Comment by moaxcp** [comment]
Yes the way the code is generated removes the need for a bunch of methods in the client unlike the C client. The requests are classes that are passed the send method of the client.

For XGrabKeyboard you create a GrabKeyboard object and use the send method on the client. The code is generated so you wont see it in github but you can check the [javadocs](https://javadoc.io/doc/com.github.moaxcp.x11/x11-client/latest/index.html) for the supported requests.
