### ISSUE TITLE
Xauthority file parsed incorrectly

### ISSUE THREAD

**Issue by Meep3692** [moaxcp/x11#31]
https://github.com/moaxcp/x11/blob/4bf8a593b104395ca3ef602dabcc23bcd36377a6/x11-protocol/x11-protocol-core/src/main/java/com/github/moaxcp/x11/protocol/XAuthority.java#L101

The current implementation reads the display number as a UTF-8 string but it should read it as a length-prefixed ASCII string. It should be noted that on my system, the length of this string is 0 for some reason. I can't find any information on what to use in this case, but I think just using 0 should be fine.

Reference: https://gitlab.freedesktop.org/xorg/lib/libxau/-/tree/master?ref_type=heads (The file format is described in the readme near the bottom)

**Comment by moaxcp** [comment]
Thanks for the reference! I don't think I have seen it. I will look into it and use 0 if the length is 0.

**Comment by moaxcp** [comment]
This should be fixed in 0.18.2.

**Comment by moaxcp** [comment]
I added a fix for this in 0.20.0. I forgot to merge the other branch before but this should work now.
