### ISSUE TITLE
Little-endian Support

### ISSUE THREAD

**Issue by jfpiv** [moaxcp/x11#39]
First off, I'd like to say thank you for developing this nifty library. It's been working great for me until I upgraded my system to Kubuntu 24.10. X servers are starting to disallow byte-swapping by default ([see this blog post](https://who-t.blogspot.com/2023/01/x-servers-no-longer-allow-byte-swapped.html)). Specifically, Xwayland now responds with `Prohibited client endianess` when a big-endian client (such as this one) attempts to connect.

The workaround is to pass `+byteswappedclients` when starting the X server, but unfortunately most Wayland compositors don't yet have an easy way to configure which options are passed to Xwayland. I think a better solution would be for this client to offer a little-endian mode if that isn't too troublesome to implement.

**Comment by moaxcp** [comment]
Thanks for the info. I think this is possible. I will have to think on it more.

**Comment by moaxcp** [comment]
I added a branch for little endian. It seems to work but there may still be issues. I noticed closing windows has an error. https://github.com/moaxcp/x11/pull/40

**Comment by moaxcp** [comment]
I started working on this again and figured it out. There was an issue with using atoms.

**Comment by moaxcp** [comment]
This was released in 0.19.0
